# Generated by Django 2.1 on 2018-08-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='category_id',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default='miguel', max_length=25),
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
