# Generated by Django 2.1 on 2018-08-05 03:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180805_0304'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('video_url', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(max_length=200, null=True)),
                ('image', models.CharField(max_length=200, null=True)),
                ('duration', models.CharField(max_length=25, null=True)),
                ('year', models.CharField(max_length=10, null=True)),
                ('clasification', models.CharField(max_length=25, null=True)),
                ('type', models.CharField(default='FREE', max_length=200)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Category')),
            ],
        ),
    ]
