# Generated by Django 2.1 on 2018-08-05 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180805_0332'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='movie',
            table='movies',
        ),
    ]
