# Generated by Django 2.1 on 2018-08-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_migration'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='migration',
            table='migrations',
        ),
    ]
