# Generated by Django 2.1 on 2018-08-10 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_auto_20180805_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[('FREE', 'FREE'), ('PREMIUM', 'PREMIUM')], default='FREE', max_length=200),
        ),
    ]
